name: CD

on:
  push:
    branches:
      - main

jobs:
  Push_To_Registry:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job Triggered"

      - name: Check out the repo
        uses: actions/checkout@v4

      - run: echo "Repository has been cloned to the Runner"

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/memoria:latest

